In [3]:
import torch

x = torch.ones(5) # input tensor
y = torch.zeros(3) # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b # gradient
loss =  torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [4]:
print(f"Gradient function for z =  {z.grad_fn}")
print(f"Gradient function for loss =  {loss.grad_fn}")

Gradient function for z =  <AddBackward0 object at 0x000001436806BEB0>
Gradient function for loss =  <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001436806B730>


# Gradient 계산하기
- 매개변수의 최적화는 손실함수의 도함수를 계산해야 한다.


In [5]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[0.0065, 0.2746, 0.0224],
        [0.0065, 0.2746, 0.0224],
        [0.0065, 0.2746, 0.0224],
        [0.0065, 0.2746, 0.0224],
        [0.0065, 0.2746, 0.0224]])
tensor([0.0065, 0.2746, 0.0224])


In [6]:
z = torch.matmul(x, w) + b
print(z.requires_grad)

True


In [7]:
with torch.no_grad():
    z = torch.matmul(x, w) +b
print(z.requires_grad)

False


In [8]:
z = torch.matmul(x,w)+b
z_det = z.detach()
print(z_det.requires_grad)

False


In [9]:
inp = torch.eye(5, requires_grad=True)
out = (inp+1).pow(2)
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"First call\n{inp.grad}")
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nSecond call\n{inp.grad}")
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph=True)
print(f"\nCall after zeroing gradients\n{inp.grad}")

First call
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])

Second call
tensor([[8., 4., 4., 4., 4.],
        [4., 8., 4., 4., 4.],
        [4., 4., 8., 4., 4.],
        [4., 4., 4., 8., 4.],
        [4., 4., 4., 4., 8.]])

Call after zeroing gradients
tensor([[4., 2., 2., 2., 2.],
        [2., 4., 2., 2., 2.],
        [2., 2., 4., 2., 2.],
        [2., 2., 2., 4., 2.],
        [2., 2., 2., 2., 4.]])
