# 파이썬 리스트에서 파이토치 텐서로

In [1]:
a = [1.0, 2.0, 1.0]
a[0]

1.0

In [2]:
a[1]

2.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

# 첫 텐서 만들어보기

In [4]:
import torch
b = torch.ones(3)
b

tensor([1., 1., 1.])

In [5]:
b[1]

tensor(1.)

In [6]:
float(b[1])

1.0

In [9]:
b[2] = 2.0

In [10]:
b

tensor([1., 1., 2.])

In [11]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
from torch import tensor


points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [13]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [14]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points.shape

torch.Size([3, 2])

In [16]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [18]:
points = torch.tensor([[4.0,1.0], [5.0,3.0], [2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [19]:
points[0,1]

tensor(1.)

In [20]:
some_list = list(range(6))
some_list[:]

[0, 1, 2, 3, 4, 5]

In [21]:
some_list[1:4]

[1, 2, 3]

In [22]:
print(some_list[1:])
print(some_list[:4])
print(some_list[:-1])


[1, 2, 3, 4, 5]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
