In [2]:
import numpy as np

In [3]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print(f'Rank of t: {t.ndim}') # 차원
print(f'Shape of t: {t.shape}') # 크기 

Rank of t: 1
Shape of t: (7,)


In [5]:
print(f't[0] t[1] t[-1]: {t[0]}, {t[1]}, {t[-1]}')

t[0] t[1] t[-1]: 0.0, 1.0, 6.0


In [6]:
print(f't[2:5] t[4:-1] {t[2:5]}, {t[4:-1]}')

t[2:5] t[4:-1] [2. 3. 4.], [4. 5.]


In [7]:
print(t[:2], t[3:])

[0. 1.] [3. 4. 5. 6.]


In [8]:
t = np.array([[1., 2., 3.,], [4., 5., 6.,], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print(f'Rank of t: {t.ndim}')
print(f'Rank of t: {t.shape}')

Rank of t: 2
Rank of t: (4, 3)


In [10]:
import torch

In [12]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [13]:
print(t.dim()) # 차원
print(t.shape) # 크기
print(t.size()) # 크기


1
torch.Size([7])
torch.Size([7])


In [14]:
print(t[0], t[1], t[-1])

tensor(0.) tensor(1.) tensor(6.)


In [15]:
t = torch.FloatTensor([[1., 2., 3.],
                        [4., 5., 6.,],
                        [7., 8., 9.,],
                        [10., 11., 12.]
                        ])
print(t)


tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [16]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [18]:
print(t[:, 1])
print(t[:, 1].size())

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [19]:
print(t[:, :-1])

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [20]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [21]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [22]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [25]:
m1 = torch.FloatTensor([[1, 2,], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f'Shape of Matrix 1: {m1.shape}')
print(f'Shape of Matrix 2: {m2.shape}')
print(m1.matmul(m2))


Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [27]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print(f'Shape of Matrix 1: {m1.shape}')
print(f'Shape of Matrix 2: {m2.shape}')
print(m1 * m2)
print(m1.mul(m2))

Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix 2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


In [28]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [29]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())

tensor(2.5000)


In [30]:
print(t.mean(dim=0))

tensor([2., 3.])


In [31]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [32]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)
print(t.sum())


tensor([[1., 2.],
        [3., 4.]])
tensor(10.)


In [33]:
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [35]:
t = torch.FloatTensor([[1, 2],
                       [3, 4]])
print(t.max())
print(t.max(dim=0))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
